Update priority_list.md
stormearthandlava/stormearthandlava.github.io pull request #45
Opened 2021-04-25 21:32 UTC by kloaf11

Changes to the priority list. Including a tip for when using WLR. Special mention for SE and EoGS combo in mplus for ST rotation. As well as updated the misconception at the bottom for SE with LB to the current suggested stack amount. Also updated the date, expansion and patch number it's current for.

2021-04-25 21:42 UTC, Bloodmallet requested changes

2021-04-25 21:42 UTC, Bloodmallet commented on guide/general/priority_list.md
> +When using { site.data.lengendary.windspeaker }}, {{ site.data.talent.sk }} and {{ site.data.talent.mote }} on single target. You can go {{ site.data.spell.lava_burst }}, {{ site.data.spell.lb }} (em
Stormkeeper should be available as `{{ site.data.talent.stormkeeper }}`, too. Generally everything that references a spell, talent, or active effect like legendary should be a link.

Same goes for the "(from WLR)". Please make WLR a link, too

2021-04-25 21:42 UTC, Bloodmallet commented on guide/general/priority_list.md
> +Combining this combo in mythic plus for single target. When you have lust up you drop hardcast lava burst from the rotation and replace with Lightning Bolt. Your new priority becomes {{ site.data.spe
Please replace `lava burst`, `Lightning Bolt`, and `lust`.

2021-04-25 22:17 UTC, Bloodmallet approved these changes
I didn't run it locally (no ruby installation available right now). Otherwise looks good.

2021-07-10 22:25 UTC, HawkCorrigan requested changes

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/covenant.md
> +{{site.data.spell.fleshcraft}} is a channeled ability that gives you a 40% HP shield for 2 minutes. While chaannelling this reduces damage taken by 20%. Also passively reduces the cooldown by consumi
typo

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/covenant.md
> +{{site.data.spell.lavish_harvest}} increases the critical hit chance of {{site.data.spell.chain_harvest}} by 10%.
either there is no change here or I am blind
doesnt matter either way

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/faq.md
> +Funneling is the act of casting {{ site.data.spell.fs }} on multiple targets in order to generate {{ site.data.spell.ls }} procs with the intention of increasing your damage on one target.
* on the main target

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/faq.md
> + {{ site.data.talent.ecs }} does not interact with procs to abilities; {{ site.data.talent.ecs }} will only echo an ability at its base.
I dont think this is understandable tbh. I also dont have too much of an idea of how to phrase it better

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/faq.md
> + It's probably because you have the pvp talent {{ site.data.talent.col }}.
should probably mention war mode

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/faq.md
> + -T5 Macro - Swaps between  {{ site.data.talent.ag }} and {{ site.data.talent.wrt }} depending on selected talent. Casts {{ site.data.talent.wrt }} at your cursor.
something went wrong here

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/faq.md
> +-T5 Macro - Swaps between :ancestral_guidance: Ancestral Guidance and :wind_rush_totem: Wind Rush Totem depending on selected talent. Casts :wind_rush_totem: Wind Rush Totem at your cursor.
something went wrong from here on out, either this is a syntax I dont know or its not converted into the link format

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/priority_list.md
> +In aoe you only cast {{ site.data.spell.cl }} and {{ site.data.spell.eq }} at 3+ targets. In ST you want to {{ site.data.spell.fs }} before casting {{ site.data.talent.se }} and with {{ site.data.spe
This probably should be reworded.

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/priority_list.md
> +With {{ site.data.spell.primoridial wave }} you still cast it on cd. Favoring to use a {{ site.data.spell.ls }} but hardcasting {{ site.data.spell.lvb }} if needed to use the {{ site.data.spell.primo
the link is broken

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/priority_list.md
> +When using {{ site.data.lengendary.windspeaker }}, {{ site.data.talent.sk }} and {{ site.data.talent.mote }} on single target. You can go {{ site.data.spell.lava_burst }}, {{ site.data.spell.lb }} (e
isnt that in the opener anyway?
if it isn't it should rather be there than in the main rotational section

2021-07-10 22:25 UTC, HawkCorrigan commented on guide/general/priority_list.md
> +**Special mention** There are many caveats with {{ site.data.talent.mote }} when in AoE situations. *IF* you have two or more {{ site.data.azerite.igneous_potential }} equipped, it is generally worth
this should just be removed and reworked completely

2021-07-10 22:34 UTC, HawkCorrigan commented
![grafik](https://user-images.githubusercontent.com/2129161/125177880-b8d73400-e1df-11eb-996c-94c0ff12236c.png)

for context

2021-11-15 16:52 UTC, Bloodmallet requested changes
I'm taking over. I grabbed your changes into a SE&L branch and will be working on that one. Thank you for the preparation. I'm just sad to see this one laying around for so long.

2021-11-15 18:22 UTC, kloaf11 commented
Thanks sorry about not being able to follow when it finally got feedback properly.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: BloodmalletEU ***@***.***>
Sent: Monday, November 15, 2021 11:52:53 AM
To: stormearthandlava/stormearthandlava.github.io ***@***.***>
Cc: kloaf11 ***@***.***>; Author ***@***.***>
Subject: Re: [stormearthandlava/stormearthandlava.github.io] Update priority_list.md (#45)


@Bloodmallet requested changes on this pull request.

I'm taking over. I grabbed your changes into a SE&L branch and will be working on that one. Thank you for the preparation. I'm just sad to see this one laying around for so long.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/stormearthandlava/stormearthandlava.github.io/pull/45#pullrequestreview-806319738>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASQAEE3XSDNAIGGXBJDNAXLUME3GLANCNFSM43RWCQOA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-11-17 21:33 UTC, merged