Bloodmallets memes blogpost
stormearthandlava/stormearthandlava.github.io pull request #51
Opened 2022-02-05 23:06 UTC by Bloodmallet

2022-02-08 19:58 UTC, HawkCorrigan requested changes
Rest looks good ^^

2022-02-08 20:27 UTC, Bloodmallet commented on blog/_posts/2022-02-15-up-and-coming-memes.md
> +1. will the return of Tier sets be exciting or trash for mythic plus?
Fixed

2022-02-08 20:30 UTC, Eokira24601 reviewed
Looks good :)

2022-02-08 20:30 UTC, Eokira24601 commented on blog/_posts/2022-02-15-up-and-coming-memes.md
> +It's time to pick them up and bring the fight to the Jailor, as the Chainer.
Jailer*

2022-02-09 16:40 UTC, Bloodmallet commented on blog/_posts/2022-02-15-up-and-coming-memes.md
> +It's time to pick them up and bring the fight to the Jailor, as the Chainer.
fixed

2022-02-10 16:44 UTC, merged